; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = core_s3

[env]
platform = espressif32
framework = arduino
upload_speed = 115200
monitor_speed = 115200

[env:core_s3]
board = m5stack-cores3
upload_port = COM6
monitor_port = COM6
build_src_filter = -<*> +<core_common/> +<core_s3/> +<shared/>
build_flags =
	-DPHASMIDA_TARGET_CORE_S3=1
lib_deps = 
	m5stack/M5Unified @ ^0.2.5
	m5stack/M5Unit-ENV @ ^1.3.2
	m5stack/M5-DLight @ ^0.0.5
	bblanchon/ArduinoJson @ ^7.0.4
	tzapu/WiFiManager @ ^2.0.17
	fastled/FastLED @ ^3.7.0
	knolleary/PubSubClient@^2.8.0

[env:atoms3_lite]
board = esp32-s3-devkitc-1 
monitor_rts = 0
monitor_dtr = 0
monitor_filters = direct
build_src_filter = -<*> +<core_common/> +<atoms3_lite/> +<shared/>
build_flags =
	-DPHASMIDA_TARGET_ATOMS3_LITE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
	m5stack/M5Unified @ ^0.2.5
	m5stack/M5Unit-ENV @ ^1.3.2
	m5stack/M5-DLight @ ^0.0.5
	bblanchon/ArduinoJson @ ^7.0.4
	tzapu/WiFiManager @ ^2.0.17
	fastled/FastLED @ ^3.7.0
	knolleary/PubSubClient@^2.8.0

[env:timer_camera_f]
board = m5stack-timer-cam
upload_port = COM7
monitor_port = COM7
build_src_filter = -<*> +<timer_camera/> +<shared/>
build_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
lib_deps = 
	bblanchon/ArduinoJson @ ^7.0.4
	tzapu/WiFiManager @ ^2.0.17
	links2004/WebSockets @ ^2.4.0
	knolleary/PubSubClient@^2.8.0
